function Demo(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Fb='&',Rb='.cache.html',_='/',lb='//',Qb=':',pb='::',Zb='<script defer="defer">Demo.onInjectionDone(\'Demo\')<\/script>',hb='<script id="',sb='=',$='?',ub='Bad handler "',Yb='DOMContentLoaded',Q='Demo',eb='Demo.nocache.js',ob='Demo::',Pb="GWT module 'Demo' may need to be (re)compiled",jb='SCRIPT',Ib='Unexpected exception in locale detection, using default: ',Hb='_',Gb='__gwt_Locale',gb='__gwt_marker_Demo',kb='base',cb='baseUrl',T='begin',S='bootstrap',Sb='cbg_button.css',bb='clear.cache.gif',rb='content',Db='default',Y='end',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',Xb='head',Nb='hosted.html?Demo',Wb='href',yb='iframe',ab='img',zb="javascript:''",Tb='link',Mb='loadExternalRefs',Cb='locale',Eb='locale=',mb='meta',Jb='mobile.user.agent',Kb='mobilesafari',Bb='moduleRequested',X='moduleStartup',nb='name',Lb='not_mobile',Ab='position:absolute;width:0;height:0;border:none',Ub='rel',db='script',Ob='selectingPermutation',R='startup',Vb='stylesheet',fb='undefined';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}Demo=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=G(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a,b){return b in v[a]}
function G(a){var b=u[a];return b==null?null:b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var b=null;var c=Db;try{if(!b){var d=location.search;var e=d.indexOf(Eb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Fb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=G(Cb)}if(!b){b=m[Gb]}if(b){c=b}while(b&&!F(Cb,b)){var h=b.lastIndexOf(Hb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Ib+a)}m[Gb]=c;return b||Db};v[Cb]={de:0,'default':1};w[Jb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Kb:Lb};v[Jb]={mobilesafari:0,not_mobile:1};Demo.onScriptLoad=function(){if(I){r=true;C()}};Demo.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Mb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Nb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Ob});if(!B()){try{alert(Pb);return;var M=K.indexOf(Qb);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+Rb}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[Sb]){var a=n.createElement(Tb);__gwt_stylesLoaded[Sb]=a;a.setAttribute(Ub,Vb);a.setAttribute(Wb,t+Sb);n.getElementsByTagName(Xb)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(Yb,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(Yb,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Mb,millis:(new Date).getTime(),type:T});n.write(Zb)}
Demo();